export const CAMPOS_MEDIDA = [
  "peso",
  "altura",
  "ombro",
  "peitoBusto",
  "cintura",
  "abdomen",
  "quadril",
  "bracoDireito",
  "bracoEsquerdo",
  "antebracoDireito",
  "antebracoEsquerdo",
  "punhoDireito",
  "punhoEsquerdo",
  "coxaDireita",
  "coxaEsquerda",
  "joelhoDireito",
  "joelhoEsquerdo",
  "panturrilhaDireita",
  "panturrilhaEsquerda",
  "tornozeloDireito",
  "tornozeloEsquerdo",
] as const;
