import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthSessionProvider } from "@/components/providers/auth-session-provider";
import { NavPrincipal } from "@/components/nav-principal";
import { auth } from "@/auth";
import { deveMostrarNavegacaoPrincipal } from "@/lib/auth/deve-mostrar-nav";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: LayoutProps<"/">) {
  const session = await auth();
  const papeis = session?.user?.papeis ?? [];
  const mostrarNav = deveMostrarNavegacaoPrincipal(
    session?.user
      ? {
          status: session.user.status,
          temConsentimento: session.user.temConsentimento,
        }
      : null,
  );

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <AuthSessionProvider>
          {mostrarNav && <NavPrincipal papeis={papeis} />}
          {children}
        </AuthSessionProvider>
      </body>
    </html>
  );
}
